#!/bin/bash


#/Prompts user for input directory path.
#/Prompts user for input permissions number (e.g. 777 to perform a chmod 777)
#/Navigates to the directory input by the user and changes all files inside it to the input setting.
#/Prints to the screen the directory contents and the new permissions settings of everything in the directory.

echo "prompt user for directory path"
read path

echo "prompt user for input permission number"
read permission

cd $path
chmod $permission *

ls -al